#!/usr/bin/env node

/**
 * forge - make-like tool
 *
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 *
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */

var toolsDir = './forge-tools';

var spawn = require('child_process').spawn,
	fs = require('fs'),
	path = require('path');

global.which = function which(program, fn) {
	if (process.platform == 'win32') {
		fn(); // no 'which' on windows
	} else {
		spawn('which', [ program ]).on('exit', fn);
	}
};

global.rootDir = __dirname;

var tools = {};
fs.readdirSync(toolsDir = path.resolve(toolsDir)).forEach(function (name) {
	var m, file = path.join(toolsDir, name);
	if (fs.statSync(file).isDirectory()) {
		if (fs.existsSync(m = path.join(file, 'index.js'))) {
			tools[name] = m;
		}
	} else if (m = name.match(/^(?!\.|_)(.+)\.js$/)) {
		tools[m[1]] = file;
	}
});

function help(err) {
	console.log('Usage: forge <tool> [options]\n');
	err && console.error(err + '\n');
	console.error('Available tools:');
	Object.keys(tools).sort().forEach(function (t) {
		console.log('   ' + t);
	});
	console.log();
	process.exit(err ? 1 : 0);
}

var args = process.argv.slice(2);
if (!args.length || args.indexOf('-h') != -1 || args.indexOf('--help') != -1) {
	help();
}

var tool = args.shift();
if (!tools[tool]) {
	help('ERROR: Invalid tool "' + tool + '"');
}

require(tools[tool]).apply(null, args);
