name: Check CLA
on:
  - pull_request

jobs:
  check-cla:
    runs-on: ubuntu-latest
    name: Check CLA

    steps:
    - env:
        GITHUB_USER: ${{ github.actor }}
      uses: tidev/tidev-cla-checker@1
